### ISSUE TITLE
typo in examples?

### ISSUE THREAD

**Issue by yoshuawuyts** [dominictarr/relative-url#1]
Shouldn't the protocol in examples be `ws` instead of `http` to create a `ws` socket? Or am I misunderstanding?

---

https://github.com/dominictarr/relative-url#examples

``` js
var location = {
  protocol: 'http',
  host: 'server.com',
  pathname '/foo'
}
```

``` txt
/ => ws://server.com/
/bar => ws://server.com/bar
//client.com => ws://client.com/
//:9999 => ws://server.com:9999/
?q=search => ws://server.com/foo?q=search
```

**Comment by dominictarr** [comment]
no, this is right, using the `protocolMap = {http: 'ws', https:'wss'}` then it will turn http into ws.
I'll update this to make it more explicit

**Comment by dominictarr** [comment]
okay check the readme again and see if that makes more sense

**Comment by yoshuawuyts** [comment]
Ah yeah, it definitely does. Thanks!
