### ISSUE TITLE
looses port

### ISSUE THREAD

**Issue by cryptix** [dominictarr/relative-url#2]
I'm getting `Error: Failed to construct 'WebSocket': Refused to connect to 'ws://localhost/' because it violates the document's Content Security Policy.` in patchwork.

Afaict the port is dropped [here](https://github.com/dominictarr/relative-url/blob/master/index.js#L45) because `port` isn't passed on.

![wsweirdness](https://cloud.githubusercontent.com/assets/111202/15894307/75c181b6-2d85-11e6-8884-b7cdd838fbf5.png)

![wsweirdness2](https://cloud.githubusercontent.com/assets/111202/15894306/75c0ab38-2d85-11e6-9a19-9c45bd616789.png)

**Comment by dominictarr** [comment]
merged into 1.0.2
